### ISSUE TITLE
"Failed to get proxy ip" after compiling.

### ISSUE THREAD

**Issue by muratulashozturk** [katant/BAS.Tor#2]
After compiling the project, running threads are ending instantly with this message "Failed to get proxy ip"
Any solution to fix it?

**Comment by muratulashozturk** [comment]
Well, after I looked at the source code, I found the solution.
For anyone who has this error, try this:
Open a folder called **custom** then open a folder called **Tor** inside the folder. Then copy the **files** folder to inside the folder.
So the directory should be like that: **custom/Tor/files/**

**Comment by katant** [comment]
![image](https://user-images.githubusercontent.com/9751407/96159851-d2cc3a80-0f1d-11eb-9971-ee559c67a469.png)
