### ISSUE TITLE
Issue with IP changing

### ISSUE THREAD

**Issue by katant** [katant/BAS.Tor#5]
There may be issue that each time that you run change IP Tor port in BAS (not your variable) reduces by 1000. This is BAS issue. For example, if your port was 9050, script reduces it by 1000 to get control port, so it will be 8050. But then when you will call it again control port will be 7050 and etc.

**Comment by muratulashozturk** [comment]
Well, you can send a signal to port with javascript. 
Take a look at https://github.com/JosephClay/signal-js

**Comment by katant** [comment]
> Well, you can send a signal to port with javascript.
> Take a look at https://github.com/JosephClay/signal-js

Issue isn't with sending. Issue is with port calculation

**Comment by muratulashozturk** [comment]
Adding 1000 at the end of code Is working? Have you ever tried it?

**Comment by katant** [comment]
Fixed in 1.6

**Comment by narfi** [comment]
hey im having an isssue with this module every time i use it, the IP adress never changed and its always the same as my home address
